## **Dataframe is most commonly used object in pandas. It is a table like datastructure containing rows and columns similar to excel spreadsheet**

In [1]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [2]:
df.shape

(6, 4)

## <font color='blue'>Rows</font>

In [3]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [4]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
df[1:3]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## <font color='blue'>Columns</font>

In [6]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [7]:
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [8]:
#see what's the type of a dataframe column, e.g 'day'

type(df["temperature"])

pandas.core.series.Series

In [9]:
# full data 
df.dtypes

day            object
temperature     int64
windspeed       int64
event          object
dtype: object

In [10]:
df['day'].dtype

dtype('O')

In [11]:
#show day and temperature of dataframe

In [12]:
df[["day", "temperature"]]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

## <font color='blue'>Operations On DataFrame</font>

In [13]:
df['temperature'].max()

35

In [14]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [15]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [18]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

1    1/2/2017
Name: day, dtype: object

In [20]:
df['day'][df['temperature'] == df['temperature'].min()]

3    1/4/2017
Name: day, dtype: object

In [21]:
#Find standard deviation of temperature

df['temperature'].std()

3.8297084310253524

In [22]:
df['temperature'].mean()

30.333333333333332

In [25]:
df['temperature'].min()

24

In [26]:
df['temperature'].max()

35

In [27]:
df['temperature'].describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [30]:
df.dtypes

day            object
temperature     int64
windspeed       int64
event          object
dtype: object

In [35]:
df['event'].max() # But mean() won't work since data type is string

'Sunny'

In [36]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

## <font color='blue'>set_index</font>

In [39]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [40]:
df.set_index('day', inplace=True)

In [41]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [42]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [43]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [44]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [45]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

In [47]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [48]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [51]:
#concatinate us and pakistani weather

df = pd.concat([pakistani_weather,us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [52]:
df = pd.concat([pakistani_weather,us_weather], ignore_index = True )
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [56]:
df = pd.concat([pakistani_weather,us_weather],keys = ['Pakistan','US'])
df

                city  temperature  humidity
Pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
US       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [63]:
#show city temperate and humidity of us cities

df.loc['US']

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [64]:
#show information of pakistani cities (city, temperature, humidity)

df.loc['Pakistan']

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [66]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [67]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [70]:
#concatenate the temperature and windspeed of Lahore, Karachi and Peshawar
df = pd.concat([temperature_df,windspeed_df],axis = 1)
df

       city  temperature     city  windspeed
0   karachi           32  karachi       12.0
1    lahore           45   lahore        7.0
2  peshawar           30      NaN        NaN

## <font color='blue'>Concatenate dataframe with series</font>

In [72]:
s = pd.Series(['humid','dry','rain'], name = 'event')

In [73]:
s

0    humid
1      dry
2     rain
Name: event, dtype: object

In [74]:
s.loc[0]

'humid'

In [75]:
con_df = pd.concat([temperature_df,s],axis = 1)
con_df

       city  temperature  event
0   karachi           32  humid
1    lahore           45    dry
2  peshawar           30   rain

## <font color="maroon"><h4 align="center">Pandas Group By</font>

In [4]:
import pandas as pd
df = pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2024  new york           32          6    Rain
1   1/2/2024  new york           36          7   Sunny
2   1/3/2024  new york           28         12    Snow
3   1/4/2024  new york           33          7   Sunny
4   1/1/2024     dubai           90          5   Sunny
5   1/2/2024     dubai           85         12     Fog
6   1/3/2024     dubai           87         15     Fog
7   1/4/2024     dubai           92          5    Rain
8   1/1/2024     paris           45         20   Sunny
9   1/2/2024     paris           50         13  Cloudy
10  1/3/2024     paris           54          8  Cloudy
11  1/4/2024     paris           42         10  Cloudy

### For this dataset, get following answers,
#### 1. What was the maximum temperature in each of these 3 cities?
#### 2. What was the average windspeed in each of these 3 cities?

In [19]:
temp_max = df.groupby('temperature')['temperature'].max()
temp_max.idxmax()

92

In [32]:
ws_avg = df.groupby('windspeed')['windspeed'].mean()
ws_avg

windspeed
5      5.0
6      6.0
7      7.0
8      8.0
10    10.0
12    12.0
13    13.0
15    15.0
20    20.0
Name: windspeed, dtype: float64

In [31]:
df['windspeed'].mean()

10.0

In [25]:
g = df.groupby('city')
g

In [6]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data:",data)

city: dubai


data:         day   city  temperature  windspeed  event
4  1/1/2024  dubai           90          5  Sunny
5  1/2/2024  dubai           85         12    Fog
6  1/3/2024  dubai           87         15    Fog
7  1/4/2024  dubai           92          5   Rain
city: new york


data:         day      city  temperature  windspeed  event
0  1/1/2024  new york           32          6   Rain
1  1/2/2024  new york           36          7  Sunny
2  1/3/2024  new york           28         12   Snow
3  1/4/2024  new york           33          7  Sunny
city: paris


data:          day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

**This is similar to SQL,**

> SELECT * from weather_data GROUP BY city

In [33]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [34]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [37]:
g.mean(numeric_only=True)

          temperature  windspeed
city
dubai           88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [38]:
# show the minimum of city group  (g)

g['city'].min()

city
dubai          dubai
new york    new york
paris          paris
Name: city, dtype: object

In [39]:
# show statistical information of g

# <font color="purple"><h3 align="center">Pandas Merge Tutorial</h3></font>

In [40]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [41]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [76]:
#merge df1 and df2 on citydf_new = pd.merge(df1 , df2 , on='city')
df_new

          temperature  humidity
city
new york           21        68
chicago            14        65
orlando            35        75

## <font color='blue'>Type Of DataBase Joins</font>

In [47]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [48]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [49]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [50]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [51]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [52]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

## <font color='blue'>indicator flag</font>

In [54]:
df3=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

        city  temperature  humidity      _merge
0  baltimore         38.0       NaN   left_only
1    chicago         14.0      65.0        both
2   new york         21.0      68.0        both
3    orlando         35.0       NaN   left_only
4  san diego          NaN      71.0  right_only

## <font color='blue'>suffixes</font>

In [55]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [56]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [57]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0

## <font color='blue'>join</font>

In [58]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

          temperature
city
new york           21
chicago            14
orlando            35

In [59]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

          humidity
city
chicago         65
new york        68
orlando         75

In [62]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [63]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [64]:
df.pivot(index='city',columns='date',values="humidity")

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [65]:
df.pivot(index='date',columns='city')

         temperature                humidity
city         beijing dubai new york  beijing dubai new york
date
5/1/2024          80    75       65       26    80       56
5/2/2024          77    78       66       30    83       58
5/3/2024          79    82       68       35    85       60

In [66]:
df.pivot(index='date',columns='city', values = 'humidity')

city      beijing  dubai  new york
date
5/1/2024       26     80        56
5/2/2024       30     83        58
5/3/2024       35     85        60

In [68]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [69]:
#replace all the negative values with NaN

df_nan = df.replace([-99999],np.nan)
df_nan

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [71]:
df_nan = df.replace(['0'],np.nan)
df_nan

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7    NaN
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5    NaN

In [73]:
df_nan = df.replace([-99999,'0'],np.nan)
df_nan

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN