## <font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          7 non-null      object
 1   temperature  7 non-null      int64
 2   windspeed    7 non-null      int64
 3   event        7 non-null      object
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [5]:
df.isna().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

**Replacing single value**

In [6]:
new_df = df.replace([-99999, 0], np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [8]:
type(df.loc[3, "event"])

str

In [9]:
new_df = df.replace([-99999, "0"], np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

**Replacing list with single value**

In [11]:
new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replace Per Column**

In [13]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

**Replacing by using mapping**

In [22]:
new_df = df.replace({
        -99999: np.nan,
        '0': 'Sunny',
    })
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0  Sunny

####List ([]) = Many Values ➜ One Value
####Mapping ({old:new}) = Each Value ➜ Different Value ✅

**Regex**

In [23]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replace list with another list**

In [24]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [27]:
df.replace(
    ['poor', 'average', 'good', 'exceptional'],
    [1, 2, 3, 4]
)

C:\Users\Leads University\AppData\Local\Temp\ipykernel_16784\3528855621.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica