# <font color="purple"><h3 align="center">Pandas Merge Tutorial</h3></font>

In [4]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [5]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [6]:
df3 = pd.merge(df1 , df2 , on = 'city')
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Type Of DataBase Joins</font>

In [20]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           22
1    chicago           14
2    orlando           35
3  baltimore           38

In [21]:
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [22]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           22        68
1   chicago           14        65
2   orlando           35        75

In [11]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore           38       NaN
1    chicago           14      65.0
2   new york           21      68.0
3    orlando           35      75.0

In [12]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35      75.0
3  baltimore           38       NaN

In [13]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

       city  temperature  humidity
0   chicago           14        65
1  new york           21        68
2   orlando           35        75

## <font color='blue'>indicator flag</font>

In [14]:
df3=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

        city  temperature  humidity     _merge
0  baltimore           38       NaN  left_only
1    chicago           14      65.0       both
2   new york           21      68.0       both
3    orlando           35      75.0       both

## <font color='blue'>suffixes</font>

In [17]:
 df4 = pd.DataFrame({
    "city": ["Lahore"],
    "temperature": [21],
})
df4

     city  temperature
0  Lahore           21

In [18]:
 df5 = pd.DataFrame({
    "city": ["Lahore"],
    "temperature": [21],
})
df5

     city  temperature
0  Lahore           21

In [23]:
df6 = pd.merge(df4 , df5 , on = 'city' , suffixes = ('Fisrt' , 'Second') )
df6

     city  temperatureFisrt  temperatureSecond
0  Lahore                21                 21

## <font color='blue'>join</font>

In [25]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

          temperature
city
new york           21
chicago            14
orlando            35

In [26]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

          humidity
city
chicago         65
new york        68
orlando         75

In [27]:
df1.join(df2,lsuffix='_l', rsuffix='_r')

          temperature  humidity
city
new york           21        68
chicago            14        65
orlando            35        75